backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: true
    slug: '{{slug}}'
    media_folder: '/src/images'
    public_folder: ''
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
